name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Stats Generales (CON PRIVADOS y SIN RANGO C)
      - name: Generate General Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          # count_private=true: Cuenta tus repos privados
          # hide_rank=true: Oculta la calificación por si acaso sigue baja
          options: username=AlanDVarela&show_icons=true&theme=radical&hide_border=true&count_private=true&hide_rank=true
          path: profile/stats.svg
          token: ${{ secrets.MY_PAT }}

      # 2. Top Lenguajes (CON PRIVADOS)
      - name: Generate Top Langs
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          # Ahora incluirá lenguajes de tus tareas privadas
          options: username=AlanDVarela&layout=compact&theme=radical&hide_border=true&count_private=true
          path: profile/top-langs.svg
          token: ${{ secrets.MY_PAT }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p profile
          git add profile/*.svg
          git commit -m "Update Private Stats" || exit 0
          git push